### ISSUE TITLE
Feedback for "Create OpenID Connect Application" with different flow

### ISSUE THREAD

**Issue by michael1011101** [SAP-docs/btp-identity-authentication#10]
Hi,

Please check what is the difference among these pages. Is it expected that the operation is same.
- [Create OpenID Connect Application for Authorization Code Flow](https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/8445e3fb8aa544559400bd20bc468599.html)
- [Create OpenID Connect Application for Client Credentials Flow](https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/98015c81af554b5d9192ad550168e331.html)
- [Create OpenID Connect Application for Resource Owner Password Credentials Flow](https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/e5b761a6237b449cb718ab47eb915b3c.html)
- [Create OpenID Connect Application for Implicit Flow](https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/b19f5e3dcdfd48149074bfa67623e84b.html)
- [Create OpenID Connect Application for JWT Bearer Flow](https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/b099d8c9624546078b8932a9cedb5094.html)

Best regards,
Michael

**Comment by ValAta** [comment]
Hi Michael,
Yes, it's one and the same operation. We'll consider simplifying the procedure just to one.
Thanks for your feedback.
BR,
Valentin
