### ISSUE TITLE
Feedback for "Configure MTCaptcha in Administration Console"

### ISSUE THREAD

**Issue by emilytheer** [SAP-docs/btp-identity-authentication#13]
https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/261d3674357d4485b9bfcdb1fabc122c.html?locale=en-US

There is a typo in the description for item 5 (Site Key - enter the Site Key provided **frpm** MTCaptcha)

**Comment by ValAta** [comment]
Hi @emilytheer,
Thanks for your comment. The typo is fixed in the documentation.
Best Regards,
Valentin
