### ISSUE TITLE
Feedback for "Application Types"

### ISSUE THREAD

**Issue by jingweiz2017** [SAP-docs/btp-identity-authentication#14]
https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/8f61880dc1c145e3ad7097e461479186.html
Quote: "Existing applications that have a parent application assigned to them will inherit only the configurations that have not been changed including the configurations that are made at the creation of the application. The configurations that are changed, and the configurations made at the creation of the application are not inherited."
Question: "the configurations made at the creation of the application" will be inherited or not?

**Comment by ValAta** [comment]
Hi @jingweiz2017, "the configurations made at the creation of the application" will not be inherited. These are the changes that can be made at the creation of the app:
![Capture](https://user-images.githubusercontent.com/48321938/210323658-34e1ecb3-7751-420b-a5a8-b1793ae165e9.PNG)
For example, if you provide Home URL or choose Type when creating a parent app, these won't be inhered in the child.
Best regards,
Valentin
