### ISSUE TITLE
Feedback for "Configure Identity Provisioning Target Systems for Real-Time User Provisioning"

### ISSUE THREAD

**Issue by sumitkhullar** [SAP-docs/btp-identity-authentication#15]
https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/334964514e8b48cb88c8ed07f5ee6a14.html?locale=en-US

The section for Real Time Provision for IPS URL for new target is not correct. This needs to be 
**Correct Entry -** 
https://<ias-tenant-host>/ipsproxy/service/api/v1/systems/<system-id>/entities/user  

**Wrong (Current entry) -**  
https://ipsproxy<provider_subaccount>-<consumer_subaccount>.<sap_cp_domain>/ipsproxy/api/v1/systems/<Identity_Authentication_source_system_id>/entities/user

**Comment by ValAta** [comment]
Hi @sumitkhullar,
Thank you very much for your feedback.
Actually both URLs are valid - one is for Identity Provisioning tenants running on the infrastructure of SAP Cloud Identity Services, while the other for tenants on the SAP BTP Neo environment. I updated the documentation accordingly.
Thanks again and best regards,
Valentin
