### ISSUE TITLE
Feedback for "Configure the Subject Name Identifier Sent to the Application"

### ISSUE THREAD

**Issue by strehle** [SAP-docs/btp-identity-authentication#19]
https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/1d020e3a3ba34c43a71fde70bfa6419a.html?locale=en-US&version=Cloud

Please correct corporateId -> corporateIdP

**Comment by ValAta** [comment]
Hi Markus.
Thanks for the feedback. The text is corrected.
BR,
Valentin
