### ISSUE TITLE
Expand the Supported Attributes table by default

### ISSUE THREAD

**Issue by gregorwolf** [SAP-docs/btp-identity-authentication#24]
### Issue description

Hello SAP Identity Authentication Documentation Team,

I would prefer if the section

"Supported Attributes Expand to view the technical names of the attributes that can take dynamic values."

would be visible by default. Because otherwise you don't find the content which is on the page when searching for a search term like [customAttribute2](https://help.sap.com/docs/identity-authentication/identity-authentication/configure-subject-name-identifier-sent-to-application?locale=en-US&q=customAttribute2).

Best Regards
Gregor

### Feedback Type (Optional)

other

### Page Title on SAP Help Portal (prefilled)

Configure the Subject Name Identifier Sent to the Application

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/identity-authentication/identity-authentication/configure-subject-name-identifier-sent-to-application?locale=en-US&q=customAttribute2

**Comment by ValAta** [comment]
Hi @gregorwolf ,
Thanks for the feedback. Now the table is expanded by default and its content is searchable.
BR
