### ISSUE TITLE
logout and introspect endpoints don't work as expected

### ISSUE THREAD

**Issue by developer992** [SAP-docs/btp-identity-authentication#25]
### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Call Identity Authentication End Session Endpoint

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/identity-authentication/identity-authentication/call-identity-authentication-end-session-endpoint

**Comment by developer992** [comment]
i make the request and the response is 302 redirect GET /login?error=invalid_login_request HTTP/1.1" 200 None

WHY ?
it says on that page the response should be :

`200 OK - Successful operation.`

but it's not 

my request:

```
access_token = "eyJhbGciOiJSUzI1NiIsImprdSI6Imh0dHBzOi8va3JrYWRldi5hdXRoZW50aWNhdGlvbi5ldXMiLCJraW........................05CBpUpCsD_hiL8u_-ZLgEpz_Fk0LoNe8A"
token = "eyJ.....jVT0ifQ"

headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Authentication': f'Bearer {access_token}',
}

data = {
    "id_token_hint": access_token,
}


r = requests.post(url, headers=headers, params=data)

```

How do i logout a user?

**Comment by developer992** [comment]
URI: `https://<tenant ID>.accounts.ondemand.com/oauth2/logout`  this doesn't work

I am making a request to my `XSUAA API URL /oauth2/logout`
with query param `?id_token_hint=eyJxgvdsfsds....`

The response code I get is:
`
HTTP/1.1" 302 0`

to
`
GET /login HTTP/1.1" 200 None`

That page says the response codes should be one of the following:

```
Result
Response Status and Error Codes
Code 	Reason 	Description
200 OK 	Successful operation. 	

User session is terminated.

If post_logout_redirect_uri isn't provided, then the user is redirected to the profile page.
400 Bad Request 	Missing or wrong parameter. 	 
```

what Am i doing wrong?

**Comment by strehle** [comment]
Can you please open a customer ticket on BC-IAM-OID, because this needs more information and we should share it via offical ticket
