### ISSUE TITLE
this has to be wrong

### ISSUE THREAD

**Issue by developer992** [SAP-docs/btp-identity-authentication#26]
### Issue description

https://help.sap.com/docs/identity-authentication/identity-authentication/call-identity-authentication-introspect-token-endpoint

it says there should be two Path parameters, `token `and `token_type_hint `but this URI 
`URI: https://<tenant ID>.accounts.ondemand.com/oauth2/introspect`  does not include these two Path params

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Call Identity Authentication Introspect Token Endpoint

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/identity-authentication/identity-authentication/call-identity-authentication-introspect-token-endpoint

**Comment by developer992** [comment]
Authentication header should probably Authorization, right?

**Comment by developer992** [comment]
why is it so hard to get help on SAP ?Forums don't work,this don't work ... documentiation is useless 
HOW DID SAP BECOME BIG AS IT IS ??? 

trully baffling

**Comment by ValAta** [comment]
Hi @developer992 ,
Thanks for your feedback. You are right - the correct type is request body. I updated the documentation and the change will be visible with the next release.
BR

**Comment by developer992** [comment]
Most appreciated.
