### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by mauriciomiao** [SAP-docs/btp-identity-authentication#29]
### Issue description

As per SAP Help https://help.sap.com/docs/identity-authentication/identity-authentication/tenant-model-and-licensing, you can also get an additional tenant with PAYG model

"To get a tenant, in addition to the test and productive tenants you're already entitled to, use self-service request. You must have a global account that uses one of the consumption-based commercial models: Cloud Platform Enterprise Agreement (CPEA) or Pay-As-You-Go for SAP BTP."

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Get Your Tenant

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/identity-authentication/identity-authentication/get-your-tenant?q=addition#get-additional-tenant

**Comment by mauriciomiao** [comment]
4626



[Image]<https://www.numenit.com/>

Mauricio Mião
Arquiteto de Solução BTP

11 98791-2505
Av. Brigadeiro Faria Lima, 4221 | 5º andar | Cj. 52
04538-133 | Itaim Bibi - São Paulo – SP

[Image]<https://linkedin.com/company/numen-brasil>[Instagram]<https://instagram.com/numen_br/>

[YouTube]<https://youtube.com/c/jointhemeeting>



[Título: Spotify]<https://open.spotify.com/show/48h4t9HxwyH6lzdDiXaUjt?si=1bWCwxG-SdKQWRC2GcXrPg&utm_source=whatsapp&dl_branch=1&nd=1>

www.numenit.com<http://www.numenit.com/>

________________________________
De: sap-doc-bot[bot] ***@***.***>
Enviado: sexta-feira, 26 de abril de 2024 04:37
Para: SAP-docs/btp-identity-authentication ***@***.***>
Cc: Mauricio Mião ***@***.***>; Mention ***@***.***>
Assunto: Re: [SAP-docs/btp-identity-authentication] Missing information (Issue #29)


Thank you for your valuable feedback contribution, @mauriciomiao<https://github.com/mauriciomiao>! So that we can recognize your contribution in the SAP Community<https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md>, please check your SAP Community user ID (this is a number) in your personal settings page<https://community.sap.com/t5/user/myprofilepage/tab/personal-profile> and share it with us in a reply to this comment. Make sure you just include the number in the reply.

Your user ID is displayed as follows:

Change display name for User ID N

where N is your user ID. For example, 53 is the user ID of the user 'qmacro'<https://community.sap.com/t5/user/viewprofilepage/user-id/53>.

Please note that we are currently refactoring our profile and badge system on the SAP Community, and will start assigning badges again when that's complete.

**Comment by IvelinaKiryakova** [comment]
Thank you for your feedback, @mauriciomiao! The requested information is now provided and released to customers.
Please refer to https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/get-your-tenant.

Best regards,
Ivelina
