### ISSUE TITLE
Feedback for "What Is Identity Authentication?"

### ISSUE THREAD

**Issue by valllo** [SAP-docs/btp-identity-authentication#4]
https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/27882717f44b445fa287936c6f43dc1f.html?locale=en-US&state=PRODUCTION&version=Cloud

The GitHub feature for the documentation is great.

**Comment by ValAta** [comment]
Thanks!
